baseURL = "https://wilonweb.github.io/multi-author/"
languageCode = "fr"
title = "ClubCode"
theme = "blowfish"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  disableFingerprinting = true
  disableSRI = true
  ShowLanguageSwitcher = true

[languages]

[languages.fr]
languageName = "Français"
weight = 1

[languages.es]
languageName = "Español"
weight = 2

[languages.ar]
languageName = "العربية"
weight = 3
[languages.ar.params]
rtl = true

[[menu.main]]
name = "Accueil"
pageRef = "/"
weight = 1

[[menu.main]]
name = "Articles"
pageRef = "/posts/"
weight = 2
