baseURL = 'https://wilonweb.github.io/multi-author/'
defaultContentLanguage = 'fr'
theme = 'blowfish'
title = 'ClubCode'

[languages]
  [languages.ar]
    contentDir = 'content/ar'
    languageName = 'العربية'
    weight = 4

    [languages.ar.menus]
      [[languages.ar.menus.main]]
        name = 'الرئيسية'
        pageRef = '/'
        weight = 1

      [[languages.ar.menus.main]]
        name = 'مقالات'
        pageRef = '/posts/'
        weight = 2

    [languages.ar.params]
      displayName = 'العربية'
      rtl = true
      slogan = 'yyy'

  [languages.en]
    contentDir = 'content/en'
    languageName = 'English'
    weight = 6

    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'Home'
        pageRef = '/'
        weight = 1

      [[languages.en.menus.main]]
        name = 'Posts'
        pageRef = '/posts/'
        weight = 2

    [languages.en.params]
      displayName = 'English'
      slogan = 'mister'

  [languages.es]
    contentDir = 'content/es'
    languageName = 'Español'
    weight = 2

    [languages.es.menus]
      [[languages.es.menus.main]]
        name = 'Inicio'
        pageRef = '/'
        weight = 1

      [[languages.es.menus.main]]
        name = 'Artículos'
        pageRef = '/posts/'
        weight = 2

    [languages.es.params]
      displayName = 'Español'
      slogan = 'cabron'

  [languages.fa]
    contentDir = 'content/fa'
    languageName = 'فارسی'
    weight = 5

    [languages.fa.menus]
      [[languages.fa.menus.main]]
        name = 'خانه'
        pageRef = '/'
        weight = 1

      [[languages.fa.menus.main]]
        name = 'مقالات'
        pageRef = '/posts/'
        weight = 2

    [languages.fa.params]
      displayName = 'فارسی'
      rtl = true
      slogan = 'popo'

  [languages.fr]
    contentDir = 'content/fr'
    languageName = 'Français'
    weight = 1

    [languages.fr.menus]
      [[languages.fr.menus.main]]
        name = 'Accueil'
        pageRef = '/'
        weight = 1

      [[languages.fr.menus.main]]
        name = 'Articles'
        pageRef = '/posts/'
        weight = 2

    [languages.fr.params]
      description = 'ClubCode : Apprends à coder facilement.'
      displayName = 'Français'
      slogan = 'monsieur'

  [languages.he]
    contentDir = 'content/he'
    languageName = 'עברית'
    weight = 3

    [languages.he.menus]
      [[languages.he.menus.main]]
        name = 'דף הבית'
        pageRef = '/'
        weight = 1

      [[languages.he.menus.main]]
        name = 'מאמרים'
        pageRef = '/posts/'
        weight = 2

    [languages.he.params]
      displayName = 'עברית'
      rtl = true
      slogan = 'jjj'

[params]
  ShowLanguageSwitcher = true
  ShowPostNavLinks = true
  ShowReadingTime = true
  defaultTheme = 'auto'
  disableFingerprinting = true
  disableSRI = true
