baseURL = ""
languageCode = "fr"
title = "ClubCode"
theme = "blowfish"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  disableFingerprinting = true
  disableSRI = true
  ShowLanguageSwitcher = true

[languages]

[languages.fr]
languageName = "Français"
contentDir = "content/fr"
weight = 1
[languages.fr.menus]
      [[languages.fr.menus.main]]
        name = 'Accueil'
        pageRef = '/'
        weight = 1
      [[languages.fr.menus.main]]
        name = 'Articles'
        pageRef = '/posts/'
        weight = 2
[languages.fr.params]
displayName = "Français"

[languages.es]
languageName = "Español"
weight = 2
[languages.es.params]
displayName = "Español"

[languages.ar]
languageName = "العربية"
weight = 3
[languages.ar.params]
rtl = true
displayName = "العربية"
