baseURL = 'https://wilonweb.github.io/multi-author/'
languageCode = 'fr-fr'
title = 'Mon blog'
theme = 'blowfish'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  disableFingerprinting = true
  disableSRI = true
