baseURL = 'https://wilonweb.github.io/multi-author/'
title = "ClubCode"
theme = 'blowfish'
defaultContentLanguage = "fr"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  disableFingerprinting = true
  disableSRI = true

[languages]
  [languages.fr]
    languageName = "Français"
    weight = 1

  [languages.es]
    languageName = "Español"
    weight = 2

  [languages.he]
    languageName = "עברית"
    weight = 3
    [languages.he.params]
      rtl = true

  [languages.ar]
    languageName = "العربية"
    weight = 4
    [languages.ar.params]
      rtl = true

  [languages.fa]
    languageName = "فارسی"
    weight = 5
    [languages.fa.params]
      rtl = true
